import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { Treatment, PatientInfo } from '../types/dental';
import { getToothById } from './toothPositions';

export async function exportTreatmentPDF(
    canvasElement: HTMLCanvasElement | null,
    treatments: Map<string, Treatment>,
    patientInfo: PatientInfo
): Promise<void> {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 15;

    // ── Header ──────────────────────────────────────────
    pdf.setFillColor(15, 23, 42); // dark slate
    pdf.rect(0, 0, pageWidth, 40, 'F');

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(22);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Dentora', margin, 18);
    pdf.setFontSize(14);
    pdf.setTextColor(47, 129, 247);
    pdf.text('Clinical Intelligence Report', margin, 24);

    // ── Patient Info ────────────────────────────────────
    let y = 52;
    pdf.setTextColor(15, 23, 42);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Patient Information', margin, y);
    y += 8;

    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Name: ${patientInfo.name}`, margin, y);
    y += 6;
    pdf.text(`Patient ID: ${patientInfo.id}`, margin, y);
    y += 6;
    pdf.text(`Date: ${patientInfo.lastVisit}`, margin, y);
    y += 12;

    // ── 3D Viewport Screenshot ─────────────────────────
    if (canvasElement) {
        try {
            const screenshot = await html2canvas(canvasElement, {
                useCORS: true,
                backgroundColor: '#0F172A',
            });
            const imgData = screenshot.toDataURL('image/png');
            const imgWidth = pageWidth - margin * 2;
            const imgHeight = (screenshot.height / screenshot.width) * imgWidth;
            pdf.addImage(imgData, 'PNG', margin, y, imgWidth, Math.min(imgHeight, 80));
            y += Math.min(imgHeight, 80) + 10;
        } catch {
            pdf.setFontSize(10);
            pdf.setTextColor(150, 150, 150);
            pdf.text('[3D viewport screenshot unavailable]', margin, y);
            y += 10;
        }
    }

    // ── Treatment Summary Table ─────────────────────────
    pdf.setTextColor(15, 23, 42);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Treatment Summary', margin, y);
    y += 8;

    if (treatments.size === 0) {
        pdf.setFontSize(11);
        pdf.setFont('helvetica', 'normal');
        pdf.text('No treatments have been applied.', margin, y);
    } else {
        // Table header
        pdf.setFillColor(226, 232, 240);
        pdf.rect(margin, y, pageWidth - margin * 2, 8, 'F');
        pdf.setFontSize(10);
        pdf.setFont('helvetica', 'bold');
        pdf.text('Tooth #', margin + 2, y + 6);
        pdf.text('Tooth Name', margin + 22, y + 6);
        pdf.text('Treatment', margin + 95, y + 6);
        pdf.text('Material', margin + 130, y + 6);
        y += 10;

        pdf.setFont('helvetica', 'normal');
        treatments.forEach((treatment) => {
            const tooth = getToothById(treatment.toothId);
            const toothNum = tooth?.toothNumber?.toString() ?? treatment.toothId;
            const toothName = tooth?.name ?? 'Unknown';
            let material = '';
            if (treatment.mode === 'CROWN') material = treatment.crownVariant ?? 'Porcelain';
            else if (treatment.mode === 'FILLING') material = treatment.fillingVariant ?? 'Composite';
            else if (treatment.mode === 'IMPLANT') material = 'Titanium';

            if (y > 270) {
                pdf.addPage();
                y = 20;
            }

            pdf.text(toothNum, margin + 2, y + 5);
            pdf.text(toothName, margin + 22, y + 5);
            pdf.text(treatment.mode, margin + 95, y + 5);
            pdf.text(material, margin + 130, y + 5);
            pdf.setDrawColor(226, 232, 240);
            pdf.line(margin, y + 7, pageWidth - margin, y + 7);
            y += 9;
        });
    }

    // ── Footer ──────────────────────────────────────────
    y = pdf.internal.pageSize.getHeight() - 25;
    pdf.setDrawColor(200, 200, 200);
    pdf.line(margin, y, pageWidth - margin, y);
    y += 6;
    pdf.setFontSize(9);
    pdf.setTextColor(150, 150, 150);
    pdf.text('This treatment plan was generated by Dentora.', margin, y);

    y += 5;
    pdf.text('Signature: ____________________________    Date: ____________', margin, y);

    pdf.save(`Treatment_Plan_${patientInfo.lastVisit}.pdf`);
}
